In [1]:
import os

import os.path
from os import path

import pandas as pd 

import wget

import json
from pandas.io.json import json_normalize

print('Libraries imported.')


dest_folder  = os.getcwd()

Libraries imported.

In [2]:
# Function to download data from a URL and save in a file.
# Input Arguments:
# - request:  the URL from where you want to downlaod the data from. 
# - folder: the file path to the folder where you want to save the downloaded file.
# - file: the name of the file to which you want to save the downloaded data.
  
def download_file(request, file):

    wget.download(request, out=file)

## Miscellenous data - 

###  * US State Names and Abbreviations
###  * US counties and Zip Codes
###  * Latitude andLongitude

In [3]:
# Dounload the count_zip data for the US if not already done

file_name = dest_folder + '\Data\county_zip.csv'

if path.exists(file_name):
    print('File Exists: ' + file_name)
    
    df_counties = pd.read_csv(file_name, names=['ZIP','COUNTY','STATE','STCOUNTYFP','CLASSFP'],
                             dtype={"ZIP": str},header=1)
    
    df_county_zip = df_counties.drop(['STATE', 'STCOUNTYFP', 'CLASSFP'], axis=1) 

    df_county_zip['COUNTY'] = df_county_zip['COUNTY'].str.split(' ').str[0].str.strip()


    
else:
    print('Downloaiing File :' + file_name)
    url = 'https://query.data.world/s/dobz6iqykhxrdkmvndle4qb2j2ny3w'
    download_file(url, file_name)
    df_counties = pd.read_csv(file_name, names=['ZIP','COUNTY','STATE','STCOUNTYFP','CLASSFP'],
                             dtype={"ZIP": str},header=1)
    
    df_county_zip = df_counties.drop(['STATE', 'STCOUNTYFP', 'CLASSFP'], axis=1) 

    df_county_zip['COUNTY'] = df_county_zip['COUNTY'].str.split(' ').str[0].str.strip()

df_county_zip.head()

File Exists: c:\Bandhin\Git\OpioidAnalysis\Data\county_zip.csv

     ZIP   COUNTY
0  36006  Autauga
1  36008  Autauga
2  36022  Autauga
3  36051  Autauga
4  36066  Autauga

In [4]:
# Dounload the state abberivations data for the website if not already done

file_name = dest_folder + '\Data\state_abb.json'

if path.exists(file_name):
    print('File Exists: ' + str(path.exists(file_name)))
    with open(file_name, 'r') as f:
            df=json.load(f)
            df_states = pd.json_normalize(df)
            #df_states = pd.read_csv(file_name)
            df_states.rename(columns={'name':'State Name',
                         'abbreviation':'State'}, inplace=True)
else:
    url = 'https://gist.githubusercontent.com/mshafrir/2646763/raw/8303e1d831e89cb8af24a11f2fa77353c317e408/states_titlecase.json'
    download_file(url, file_name)
    with open(file_name, 'r') as f:
            df=json.load(f)
            df_states = pd.json_normalize(df)
            #df_states = pd.read_csv(file_name)
            df_states.rename(columns={'name':'State Name',
                         'abbreviation':'State'}, inplace=True)
df_states.head()

File Exists: True

       State Name State
0         Alabama    AL
1          Alaska    AK
2  American Samoa    AS
3         Arizona    AZ
4        Arkansas    AR

In [5]:
# Dounload the latitude and longitude data for New Jersery Counties if not already done

file_name = dest_folder + '/Data/nj_zipcode_geo.json'

if path.exists(file_name):
    print('File Exists: ' + str(path.exists(file_name)))
else:
    url = 'https://raw.githubusercontent.com/deldersveld/topojson/master/countries/us-states/NJ-34-new-jersey-counties.json'
    download_file(url, file_name)

File Exists: True

In [6]:
# Dounload the latitude and longitude data for US States if not already done

file_name = dest_folder + '/Data/state_geo.json'

if path.exists(file_name):
    print('File Exists: ' + str(path.exists(file_name)))
else:
   # url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json'
    url = 'https://gist.githubusercontent.com/meiqimichelle/7727723/raw/0109432d22f28fd1a669a3fd113e41c4193dbb5d/USstates_avg_latLong'
    download_file(url, file_name)

File Exists: True

In [7]:
# Dounload the latitude and longitude data for US Counties if not already done

file_name = dest_folder + '\Data\county_geo.json'

if path.exists(file_name):
    print('File Exists: ' + file_name)
else:
    print('Downloding File: ' + file_name)
    url = 'https://raw.githubusercontent.com/python-visualization/folium/master/tests/us-counties.json'
    download_file(url, file_name)

File Exists: c:\Bandhin\Git\OpioidAnalysis\Data\county_geo.json

## Opioid Prescription dataset

This dataset is about Medicare Part D Opioid Prescriber Summary File 2017. https://data.cms.gov/api/views/sakz-a2rp/rows.csv?accessType=DOWNLOAD  
This dataset is about Medicare Part D Opioid Prescriber Summary File 2016. https://data.cms.gov/api/views/6wg9-kwip/rows.csv?accessType=DOWNLOAD  
This dataset is about Medicare Part D Opioid Prescriber Summary File 2015. https://data.cms.gov/api/views/6i2k-7h8p/rows.csv?accessType=DOWNLOAD  
This dataset is about Medicare Part D Opioid Prescriber Summary File 2014. https://data.cms.gov/api/views/e4ka-3ncx/rows.csv?accessType=DOWNLOAD  
This dataset is about Medicare Part D Opioid Prescriber Summary File 2013. https://data.cms.gov/api/views/yb2j-f3fp/rows.csv?accessType=DOWNLOAD  


The **Opioid_data.csv** data set includes details  on the individual opioid prescribing rates of health providers . It includes following fields:  

| Field                     | Description                         |
|---------------------------|-------------------------------------|
| NPI                       | Provider Identification Number      |
| NPPES Provider Last Name  | Provider Last Name                  |
| NPPES Provider First Name | Provider First Name                 |
| NPPES Provider Zip Code   | Provider Zip Code                   |
| NPPES Provider State      | Provider State                      |
| Speciality Description    | Provider Speciality                 |
| Total Claim Count         | Total Claims for by provider                   |
| Opioid Claim Count        | Opioid Claim by provider                  |
| Opioid Prescribing Rate   | Opioid Prescribing Rate             |
| Long Acting Opioid Count  | Long Acting Opioid Claim by provider           |
| Long Acting Opioid Prescribing Rate | Long Acting Opioid Prescribing Rate |
|                           |                                     |

### CSV Files

In [8]:
### Load Opioid Prescription data for 2017, 2016,2015, 2014, 2013 CSV files from Medicare Part D

# Create a dataframe with the loaded cvs file

#dest_folder = os.path.join("Bandhin", "Git", "Opioid-Analysis", "Data")

years =['2017', '2016', '2015', '2014', '2013']

d = {}

for year in years:
    d[year] = pd.DataFrame()
    file_name = dest_folder + '\Data\opioid_data_' + year + '.csv'
    #file_name = os.path.join(dest_folder, file_name)
   
    d[year] = pd.read_csv(file_name,names=['NPI','NPPES_last_name','NPPES_first_name','NPPES_zip_code','NPPES_state','Speciality_Description','Total_Claim_Count','Opioid_Claim_Count',
                                                           'Opioid_Prescribing_Rate','Long-Acting_Opioid_Claim_Count','Long-Acting_Opioid_Prescribing_Rate'],
                             dtype={"NPPES_zip_code": str, "NPI":str},header=1)
    d[year]['YEAR'] = year
    display(d[year].head())

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003804923,KASTENDIECK,KURT,87505,NM,Family Practice,5342,593.0,11.10,72.0,12.14,2017
1,1366761108,WILEY,JULIE,73102,OK,Obstetrics & Gynecology,125,NaN,NaN,0.0,NaN,2017
2,1386611234,GUNNELL,JENNIFER,97701,OR,Internal Medicine,250,NaN,NaN,0.0,NaN,2017
3,1871920066,COX,SUSAN,89502,NV,Nurse Practitioner,717,0.0,0.00,0.0,NaN,2017
4,1437118023,HOBDY,CYNTHIA,35020,AL,Podiatry,578,72.0,12.46,0.0,0.00,2017

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1733,941.0,54.30,165.0,17.53,2016
1,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,49,11.0,22.45,0.0,0.00,2016
2,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,146,NaN,NaN,0.0,NaN,2016
3,1003000407,GIRARDI,DAVID,15825,PA,Family Practice,2225,17.0,0.76,NaN,NaN,2016
4,1003000423,VELOTTA,JENNIFER,44106,OH,Obstetrics & Gynecology,170,NaN,NaN,0.0,NaN,2016

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1757,847.0,48.21,174.0,20.54,2015
1,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,43,16.0,37.21,0.0,0.00,2015
2,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,15,0.0,0.00,0.0,NaN,2015
3,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,114,21.0,18.42,0.0,0.00,2015
4,1003000407,GIRARDI,DAVID,15825,PA,Family Practice,1388,26.0,1.87,NaN,NaN,2015

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1757,847.0,48.21,174.0,20.54,2014
1,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,43,16.0,37.21,0.0,0.00,2014
2,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,15,0.0,0.00,0.0,NaN,2014
3,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,114,21.0,18.42,0.0,0.00,2014
4,1003000407,GIRARDI,DAVID,15825,PA,Family Practice,1388,26.0,1.87,NaN,NaN,2014

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1757,847.0,48.21,174.0,20.54,2013
1,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,43,16.0,37.21,0.0,0.00,2013
2,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,15,0.0,0.00,0.0,NaN,2013
3,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,114,21.0,18.42,0.0,0.00,2013
4,1003000407,GIRARDI,DAVID,15825,PA,Family Practice,1388,26.0,1.87,NaN,NaN,2013

### JSON Files

In [9]:
### Load Opioid Prescription data for 2017, 2016,2015, 2014, 2013 JSON files from Medicare Part D

   
data_urls = {'2017':'https://data.cms.gov/resource/sakz-a2rp.json', 
          '2016':'https://data.cms.gov/resource/6wg9-kwip.json',
          '2015':'https://data.cms.gov/resource/6i2k-7h8p.json',
          '2014':'https://data.cms.gov/resource/e4ka-3ncx.json',
          '2013':'https://data.cms.gov/resource/yb2j-f3fp.json'}

d = {}

for key in data_urls:
    d[key] = pd.DataFrame()
    file_name = dest_folder + '\Data\opioid_data_' + key + '.json'
    #file_name = os.path.join(dest_folder, file_name)
    
    if path.exists(file_name):
        print('File Exists: ' + str(path.exists(file_name)) + ' ' + file_name)
        with open(file_name, 'r') as f:
            df=json.load(f)
            d[key] = pd.json_normalize(df)
            
            d[key].columns = ['NPI','NPPES_last_name','NPPES_first_name','NPPES_zip_code','NPPES_state','Speciality_Description','Total_Claim_Count','Opioid_Claim_Count',
                         'Opioid_Prescribing_Rate','Long-Acting_Opioid_Claim_Count','Long-Acting_Opioid_Prescribing_Rate']
            d[key] = d[key].astype({"NPPES_zip_code": str, "NPI":str})
            d[key]['YEAR'] = key
            display(d[key].head())
    else:
        url = data_urls[key]
        print('URL: ' + url)
        download_file(url, file_name)
        
        d[key] = pd.DataFrame()
        
        with open(file_name, 'r') as f:
            df=json.load(f)
            d[key] = pd.json_normalize(df)
            
            d[key].columns = ['NPI','NPPES_last_name','NPPES_first_name','NPPES_zip_code','NPPES_state','Speciality_Description','Total_Claim_Count','Opioid_Claim_Count',
                         'Opioid_Prescribing_Rate','Long-Acting_Opioid_Claim_Count','Long-Acting_Opioid_Prescribing_Rate']
            d[key] = d[key].astype({"NPPES_zip_code": str, "NPI":str})
            d[key]['YEAR'] = key
            display(d[key].head())

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_data_2017.json

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000126,ENKESHAFI,ARDALAN,21502,MD,Internal Medicine,677,25,3.6927621861,NaN,NaN,2017
1,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1946,1040,53.442959918,200,19.230769231,2017
2,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,55,14,25.454545455,0,0,2017
3,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,18,0,0,0,NaN,2017
4,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,90,0,0,0,NaN,2017

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_data_2016.json

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000126,ENKESHAFI,ARDALAN,21502,MD,Internal Medicine,545,23,4.2201834862,NaN,NaN,2016
1,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1733,941,54.298903635,165,17.534537726,2016
2,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,49,11,22.448979592,0,0,2016
3,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,146,NaN,NaN,0,NaN,2016
4,1003000407,GIRARDI,DAVID,15825,PA,Family Practice,2225,17,0.7640449438,NaN,NaN,2016

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_data_2015.json

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000126,ENKESHAFI,ARDALAN,21502,MD,Internal Medicine,825,38,4.6060606061,NaN,NaN,2015
1,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,1757,847,48.207171315,174,20.54309327,2015
2,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,43,16,37.209302326,0,0,2015
3,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,15,0,0,0,NaN,2015
4,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,114,21,18.421052632,0,0,2015

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_data_2014.json

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000126,ENKESHAFI,ARDALAN,21502,MD,Internal Medicine,675,37,5.4814814815,NaN,NaN,2014
1,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,937,425,45.357524013,36,8.4705882353,2014
2,1003000159,VOGES,MARSHA,29405,SC,Nurse Practitioner,18,NaN,NaN,0,NaN,2014
3,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,58,18,31.034482759,0,0,2014
4,1003000282,BLAKEMORE,ROSIE,37243,TN,Nurse Practitioner,14,0,0,0,NaN,2014

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_data_2013.json

,NPI,NPPES_last_name,NPPES_first_name,NPPES_zip_code,NPPES_state,Speciality_Description,Total_Claim_Count,Opioid_Claim_Count,Opioid_Prescribing_Rate,Long-Acting_Opioid_Claim_Count,Long-Acting_Opioid_Prescribing_Rate,YEAR
0,1003000126,ENKESHAFI,ARDALAN,21502,MD,Internal Medicine,363,16,4.4077134986,NaN,NaN,2013
1,1003000142,KHALIL,RASHID,43623,OH,Anesthesiology,512,252,49.21875,29,11.507936508,2013
2,1003000167,ESCOBAR,JULIO,89403,NV,Dentist,69,24,34.782608696,0,0,2013
3,1003000175,REYES-VASQUEZ,BELINDA,91744,CA,Dentist,13,NaN,NaN,0,NaN,2013
4,1003000183,CYPHERS,DENNIS,98467,WA,Massage Therapist,82,NaN,NaN,0,NaN,2013

In [10]:
                             
file_name = dest_folder + '\Data\opioid_total_us.csv'

if path.exists(file_name):
    print('File Exists: ' + str(path.exists(file_name)) + ' ' + file_name)
else:
    df_opioid_total = pd.concat([d['2017'], d['2016'], d['2015'], d['2014'], d['2013']])\
        .groupby(['NPI','NPPES_last_name','NPPES_first_name','NPPES_zip_code','NPPES_state','Speciality_Description','YEAR'])['Total_Claim_Count','Opioid_Claim_Count','Long-Acting_Opioid_Claim_Count']\
        .sum().reset_index()
    df_opioid_US = pd.merge(df_opioid_total,df_county_zip, left_on='NPPES_zip_code',right_on='ZIP')
    #df_opiod_total.to_cvs('C:\Bandhin\Git\Opioid-Analysis\Data\opioid_total.csv')
    df_opioid_US.to_csv('C:\Bandhin\Git\Opioid-Analysis\Data\opioid_total_us.csv')

File Exists: True c:\Bandhin\Git\OpioidAnalysis\Data\opioid_total_us.csv